### ISSUE TITLE
Can I Help.

### ISSUE THREAD

**Issue by Voltern** [VutonDesign/SimplePick#4]
I Have Created Something like this before
AND I PROMISE NOT TO COPTY WORK.

**Comment by VutonDesign** [comment]
There's nothing that really needs to be done anymore, but I'll let you know if I find something.

**Comment by Voltern** [comment]
Can i be a Qa?

**Comment by VutonDesign** [comment]
Eh, Okay. Just check every new PR and leave a comment with ```qa-ok``` or ```qa-needs-work``` and I'll change the label.

**Comment by Voltern** [comment]
Thanks
