### ISSUE TITLE
I LOVE IT!

### ISSUE THREAD

**Issue by redmangospros** [VutonDesign/SimplePick#7]

**Comment by redmangospros** [comment]
[SimplePick-master (5).zip](https://github.com/VutonDesign/SimplePick/files/1485226/SimplePick-master.5.zip)

**Comment by redmangospros** [comment]
![k](https://user-images.githubusercontent.com/21000033/32986632-78062e08-cca4-11e7-991b-1e7e82bd2e74.png)

**Comment by VutonDesign** [comment]
Thanks
